fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run mypy docling_parse tests
        pass_filenames: false
        language: system
        files: '\.py$'
#  - repo: local
#    hooks:
#      - id: pytest
#        name: Pytest
#        entry: poetry run pytest tests/
#        pass_filenames: false
#        language: system
#        files: '\.py$'	
  - repo: local
    hooks:
      - id: system
        name: Poetry check
        entry: poetry check --lock
        pass_filenames: false
        language: system
